/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_intent_free: (a: number, b: number) => void;
export const __wbg_intentwithtag_free: (a: number, b: number) => void;
export const __wbg_network_free: (a: number, b: number) => void;
export const __wbg_openintent_free: (a: number, b: number) => void;
export const __wbg_transactionreadyforsigning_free: (a: number, b: number) => void;
export const add_tx: (a: number, b: number, c: number, d: number, e: bigint, f: number, g: number, h: number) => [number, number, number];
export const close_tx: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const fee_buffer: () => bigint;
export const intent_add: (a: bigint) => number;
export const intent_close: () => number;
export const intentwithtag_intent: (a: number) => number;
export const intentwithtag_new: (a: number, b: number, c: number) => number;
export const intentwithtag_tag: (a: number) => [number, number];
export const min_ada_buffer: () => bigint;
export const network_mainnet: () => number;
export const network_preprod: () => number;
export const network_preview: () => number;
export const open_tx: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: bigint, k: bigint) => [number, number, number];
export const openintent_adaptorVk: (a: number) => [number, number];
export const openintent_amount: (a: number) => bigint;
export const openintent_closePeriodSec: (a: number) => bigint;
export const openintent_new: (a: number, b: number, c: number, d: number, e: bigint, f: bigint) => number;
export const openintent_tag: (a: number) => [number, number];
export const transactionreadyforsigning_getId: (a: number) => [number, number];
export const transactionreadyforsigning_sign: (a: number, b: number, c: number) => [number, number];
export const transactionreadyforsigning_toCbor: (a: number) => [number, number];
export const tx: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number];
export const enableLogsAndPanicHook: (a: number) => [number, number];
export const __wbg_error_free: (a: number, b: number) => void;
export const error_message: (a: number) => [number, number];
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_alloc: () => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
